apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poc-nginx
  template:
    metadata:
      labels:
        app: poc-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.5
        ports:
        - containerPort: 80
