apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis-sample
  template:
    metadata:
      labels:
        app: redis-sample
    spec:
      containers:
        - name: redis
          image: redis:7.2.4
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: ClusterIP
  selector:
    app: redis-sample
  ports:
    - port: 6379
      targetPort: 6379
